### ISSUE TITLE
Discussion: Best way to save list of package requests

### ISSUE THREAD

**Issue by krpaulson** [ihmeuw-demographics/docker-base#27]
**Is this related to a specific problem or scenario? Please describe.**
Sometimes I realize R packages I wish were included in this image, but do not have time to add them.

**Describe possible standards, solutions or other ideas**
One option might be to keep an open issue with a list.
Or, we could add a page to the wiki.

**Questions to discuss**
What is the best way to catalog a list of R package requests?

**Additional context**
In this particular instance, I was wishing the image had `ggrepel` installed.

**Comment by chacalle** [comment]
Maybe we can have an open issue for each v{gbd_year}.{release} that people can list basic R packages and python packages they want installed?

**Comment by krpaulson** [comment]
That sounds good to me.
