### ISSUE TITLE
FEATURE: v2020.0 package requests

### ISSUE THREAD

**Issue by krpaulson** [ihmeuw-demographics/docker-base#28]
This issue should remain open until the final version of v2020.0 is built. This issue will be checked as new versions of the image are rebuilt.

**R package requests**

- [x]  `ggrepel` : commonly used pacakge for text labels in ggplot

- [x] `openxlsx` : for table formatting for papers

- [x] `pacman` : for loading in R packages concisely and installing if missing

- [x] `readstata13`: for reading in stata files produced by legacy code

- [x] `rjson`: for some old code which uses json configs

- [x] `demogR`: not needed yet but could be nice to include.

- [x] `HMDHFDplus`: for downloading HMD data. Not needed but could be nice.

- [x] `pscl`: includes zero-inflated poisson regression

- [x] `profvis`: interactive Visualizations for Profiling R Code

- [x] `bench`: High Precision Timing of R Expressions

- [x] `janitor`: Simple tools for data cleaning in R

- [x] `visNetwork`: interactive network visualizations

- [x]  `arm`: data analysis using regression and multilevel/hierarchical models

- [x] `reprex`: Render bits of R code for sharing

- [x] `demogsurv`

- [x] `aweek` : convert date to week by specifying any week start day

**Python package requests**

- [x] `regmod`: mscm-team modeling package, but pip installable

- [x] `matplotlib`: plotting -- check because this might be in the container already

- [x] `pyyaml`: for working with yaml config files

- [x] `emmodel`: msmc-team modeling package, pip installable

**Comment by krpaulson** [comment]
@chacalle FYI

**Comment by chacalle** [comment]
I updated the title and description to be specific to v2020.0

Also remember you can temporarily install packages in our singularity image, but then should add to this list so that they are permanently included in future docker images.
